### PR TITLE
10.11 DP1 v2

### PR DESCRIPTION
**Pull request by erikng**
I attempted to see if I could pull down DP2 and I got 15A179w instead.

Odd.

### CODE REVIEW

**Comment by MagerValp** [comment]
Weird. Traveling, so I can't verify. Merging, thanks!

**Comment by MagerValp** [comment]
Oh, just noticed that the timestamp hasn't been updated. Run autodmg-verify.py to check.

**Comment by erikng** [comment]
Corrected.

**Comment by arubdesu** [comment]
I see these as being pulled by softwareupdated on a clean bare metal install(~2011 hardware, but)...
```
http://swcdn.apple.com/content/downloads/43/42/031-04978/8jijjdt3ep0y9xe20a356wst771fckd2de/kdrl.pkg
http://swcdn.apple.com/content/downloads/30/18/031-22462/5ry1qymwudgywzhlg8al2s1c234x03phrx/XProtectPlistConfigData_1011.pkg
http://swcdn.apple.com/content/downloads/29/01/031-25195/fdgzh7mfwoi1uowjn7crff1rg1axp4vvpt/GatekeeperConfigData.pkg
http://swcdn.apple.com/content/downloads/07/10/031-25506/wy6k3cd22jejq1j83kmahud7zwbaxid2z6/OSXUpd10.11.pkg
http://swcdn.apple.com/content/downloads/07/10/031-25506/wy6k3cd22jejq1j83kmahud7zwbaxid2z6/FirmwareUpdate.pkg
http://swcdn.apple.com/content/downloads/07/10/031-25506/wy6k3cd22jejq1j83kmahud7zwbaxid2z6/OSXUpd10.11Patch.pkg
http://swcdn.apple.com/content/downloads/15/54/031-25507/rjki32of9yi5zydmfv8o9v04h7s3b3vw0c/RecoveryHDUpdate.pkg
```
With these short descriptions:
```
031-04978	 | CoreLSKD Configuration Data 8
031-22462	 | XProtectPlistConfigData 1.0
031-25195	 | Gatekeeper Configuration Data 69
031-25506	 | OS X El Capitan Developer Beta 2 1.0
031-25507	 | El Capitan Recovery Update 1.0
```

**Comment by erikng** [comment]
Posted this on Twitter but the build differences are: AppleSeed vs Developer Beta.

**Comment by erikng** [comment]
Also, I've been trying to figure out the difference between OSXUpd10.11.pkg and OSXUpd10.11Pach.pkg.

**Comment by arubdesu** [comment]
Pardon, it doesn't actually use the OSXUpd10.11.patch. The actual three packages and URLs are:
```
http://swcdn.apple.com/content/downloads/07/10/031-25506/wy6k3cd22jejq1j83kmahud7zwbaxid2z6/OSXUpd10.11.pkg
http://swcdn.apple.com/content/downloads/07/10/031-25506/wy6k3cd22jejq1j83kmahud7zwbaxid2z6/FirmwareUpdate.pkg
http://swcdn.apple.com/content/downloads/15/54/031-25507/rjki32of9yi5zydmfv8o9v04h7s3b3vw0c/RecoveryHDUpdate.pkg
```
screen shot 2015-06-25 at 11 05 17 am

**Comment by erikng** [comment]
Thanks. Those were the exact packages I was testing with yesterday. I'm not entirely sure what the patch is for.

**Comment by MagerValp** [comment]
I'm traveling and all I have is my iPhone, so I can't verify anything, but if this was beta seed and not DP, it shouldn't be merged should it? Maybe profiles for both are needed?

**Comment by arubdesu** [comment]
My take is we're not going to be worried about generating images for public betas(which I believe aren't supposed to actually start going out for ElCap until next month anyway AFAIK), we've only been working on DP's. 
@MagerValp sound about right? @erikng want me to make a fork/topic branch/PR?

**Comment by erikng** [comment]
Either way. For clarification I know what happened. 

One of my accounts was invited to the AppleSeed while my other account is in the developer preview. I wasn't really paying attention at some point, so I made the profile and created an AppleSeed image. 

The main difference between the two images are the connecting SUS catalog and the reporting tools. I'm not sure if there will be another catalog for the public beta.

Perhaps we should revert the PR as the AppleSeed is technically NDA.

**Comment by erikng** [comment]
Let's close this.

**Pull request closed without merging**
