### PR TITLE
Updates for Safari, iTunes, Security

### PR DESCRIPTION
**Pull request by 128keaton**
Added:
- Security Update 2019-001 (Sierra)
- Safari 12.1 for High Sierra
- Safari 12.1 for Sierra
- iTunes 12.8.2 (Sierra)

### CODE REVIEW

**Comment by MagerValp** [comment]
Much obliged! Merging.

**Comment by MagerValp** [comment]
Maybe I was a little quick on the button there, doesn't look like the security update and iTunes was in this PR? Either way, Safari 12.1 looks good.

**Comment by 128keaton** [comment]
My bad, ugh. I'll see if I can get the changes back from my other branch. Thanks!

**Comment by MagerValp** [comment]
Ah!

**Pull request merged**
