### PR TITLE
ARD 3.9.2

### PR DESCRIPTION
**Pull request by macprince**
Update UpdateProfiles.plist for Apple Remote Desktop Client 3.9.2

### CODE REVIEW

**Comment by macprince** [comment]
This is the first time I've ever tried to do one of these, so apologies in advance for whatever I may get wrong.

**Comment by erikng** [comment]
Did Apple not release a DMG for this?

**Comment by macprince** [comment]
@erikng It appears not, at least not yet. The latest on their support site is this, which is 3.9.0: https://support.apple.com/kb/DL1909

**Comment by erikng** [comment]
Okay. I will hold off on merging and defer this to @MagerValp then.

**Comment by MagerValp** [comment]
Diff looks good, and as long as the images checked out I'm ok to merge.

**Comment by MagerValp** [comment]
Looks good here, merging!

**Pull request merged**
