### PR TITLE
Original URL deprecated (metadata/dist only?)

### LINKED ISSUE #44: Safari 9.1.3 package has invalid URL
Currently the URL for the Safari 9.1.3 update for Mavericks errors with 404

### PR DESCRIPTION
**Pull request by arubdesu**
It checksums the same, but is at a new URL. Fixes #44

### CODE REVIEW

**Comment by MagerValp** [comment]
New URL, same checksum?

**Comment by arubdesu** [comment]
Yup, I ran `openssl sha1` on the new download and it spit out the same value as was there previously

**Comment by MagerValp** [comment]
Huh, interesting. Would you mind running `autodmg-checksum.py` and `autodmg-verify.py` on it to bump the `PublicationDate` before I merge?

**Comment by arubdesu** [comment]
Sure, will do later today

**Comment by MagerValp** [comment]
Perfect, thanks!

**Pull request merged**
